# AllCops:
#   Exclude:
#     - "README.md"
#     - "Guardfile"
#     - "Rakefile"

#   DisplayCopNames: true

# Layout/LineLength:
#   Max: 1200
# Metrics/MethodLength:
#   Max: 200
# Metrics/AbcSize:
#   Max: 50
# Metrics/ClassLength:
#   Max: 150
# Metrics/BlockLength:
#   ExcludedMethods: ['describe']
#   Max: 30


# Style/Documentation:
#   Enabled: false
# Style/ClassAndModuleChildren:
#   Enabled: false
# Style/EachForSimpleLoop:
#   Enabled: false
# Style/AndOr:
#   Enabled: false
# Style/DefWithParentheses:
#   Enabled: false
# Style/FrozenStringLiteralComment:
#   EnforcedStyle: never

# Layout/HashAlignment:
#   EnforcedColonStyle: key
# Layout/ExtraSpacing:
#   AllowForAlignment: false
# Layout/MultilineMethodCallIndentation:
#   Enabled: true
#   EnforcedStyle: indented
# Style/HashEachMethods:
#   Enabled: false
# Style/HashTransformKeys:
#   Enabled: false
# Style/HashTransformValues:
#   Enabled: false
# Lint/RaiseException:
#   Enabled: true
# Lint/StructNewOverride:
#   Enabled: false

AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
Metrics/ModuleLength:
  Enabled: false
  


Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never


Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

  Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false